apiVersion: apps/v1
kind: Deployment
metadata:
  name: adkar47-final-redis-deployment
  labels:
    username: adkar47
    env: test
    app: adkar47-final-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adkar47-final-redis
  template:
    metadata:
      labels:
        app: adkar47-final-redis
    spec:
      containers:
        - name: redis-container
          image: redis:5.0.0
          volumeMounts:
          - name: redis-adkar47-final
            mountPath: "/data"
      volumes:
      - name: redis-adkar47-final
        persistentVolumeClaim:
          claimName: adkar47-final-redis-pvc
