apiVersion: v1
kind: Service
metadata:
  name: adkar47-final-redis-service
  labels:
    username: adkar47
    env: test
spec:
  type: ClusterIP
  selector:
    app: adkar47-final-redis
  ports:
  - name: adkar47-redis
    port: 6379
    targetPort: 6379
