apiVersion: apps/v1
kind: Deployment
metadata:
  name: adkar47-final-flask-deployment
  labels:
    app: adkar47-final-flask
    username: adkar47
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adkar47-final-flask
  template:
    metadata:
      labels:
        app: adkar47-final-flask
    spec:
      containers:
        - name: flask-container
          imagePullPolicy: Always
          image: adkar47/adkar47-final
          command: ['python3', 'api.py']
          env:
          - name: FlaskApp
            value: "api.py"
          ports:
          - name: http
            containerPort: 5000
