---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adkar47-test-flask-deployment
  labels:
    username: adkar47
    env: test
    app: adkar47-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adkar47-test-flask
  template:
    metadata:
      labels:
        app: adkar47-test-flask
    spec:
      containers:
        - name: flask-latest
          image: adkar47/homework06_flask:latest
