apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-adkar47-test
  labels:
    username: adkar47
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
