apiVersion: apps/v1
kind: Deployment
metadata:
  name: adkar47-hw7-worker-deployment
  labels:
    app: adkar47-hw7-worker
    username: adkar47
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adkar47-hw7-worker
  template:
    metadata:
      labels:
        app: adkar47-hw7-worker
        username: adkar47
        env: test
    spec:
      containers:
        - name: worker-container
          imagePullPolicy: Always
          image: adkar47/adkar47-hw7
          env:
            - name: "WORKER_IP"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WORKER
              value: "worker.py"
          ports:
          - name: http
            containerPort: 5000
